name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username:  ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
        ecr: auto 
        logout: true 
                      
    - name: Build and publish the image
      run: |
        docker build . --tag ghcr.io/jdwv/kustom-ubuntu-jammy:latest
        docker push ghcr.io/jdwv/kustom-ubuntu-jammy:latest
